CREATE FUNCTION dbo.UFN_SUBSTITUI_NUMEROS(@TEXTO varchar(500))
RETURNS varchar(500)
BEGIN
DECLARE @INICIO int
SET @INICIO = PATINDEX('%[0-9]%', @TEXTO)

WHILE @INICIO > 0
BEGIN
	SET @INICIO = PATINDEX('%[0-9]%', @TEXTO)
	IF @INICIO > 0
	  BEGIN
		SET @TEXTO = REPLACE(@TEXTO, SUBSTRING(@TEXTO, @INICIO, 1),'X')
	  END
	ELSE
	  BEGIN
		BREAK;
	  END
END
RETURN @TEXTO
END
GO

SELECT dbo.UFN_SUBSTITUI_NUMEROS('Operação-marco 0030 da sequência 0 na ordem 1344106 ainda não foi confirmada');
GO