CREATE TABLE TB_ALVO 
(
CD_PESSOA int	IDENTITY(1, 1),
NM_PESSOA varchar(30),
CONSTRAINT PK_ALVO PRIMARY KEY(CD_PESSOA)
);

CREATE TABLE TB_ORIGEM 
(
CD_PESSOA int,
NM_PESSOA varchar(30),
CONSTRAINT PK_ORIGEM PRIMARY KEY(CD_PESSOA));
GO

INSERT TB_ALVO(NM_PESSOA) VALUES('Jose');
INSERT TB_ALVO(NM_PESSOA) VALUES('João');
INSERT TB_ALVO(NM_PESSOA) VALUES('Durval');
GO

INSERT TB_ORIGEM(CD_PESSOA, NM_PESSOA) Values(103, 'Miguel');
INSERT TB_ORIGEM(CD_PESSOA, NM_PESSOA) Values(104, 'Sandro');
GO


SELECT * FROM TB_ALVO
SELECT * FROM TB_ORIGEM

MERGE TB_ALVO AS A
USING TB_ORIGEM AS O
ON (A.CD_PESSOA = O.CD_PESSOA)
WHEN NOT MATCHED BY TARGET AND O.NM_PESSOA LIKE 'S%'
	THEN INSERT(NM_PESSOA) VALUES(O.NM_PESSOA)
WHEN MATCHED
	THEN UPDATE SET A.NM_PESSOA = O.NM_PESSOA
WHEN NOT MATCHED BY SOURCE AND A.NM_PESSOA LIKE 'S%'
	THEN DELETE;
GO

SELECT * FROM TB_ALVO
SELECT * FROM TB_ORIGEM
GO

DROP TABLE TB_ALVO
DROP TABLE TB_ORIGEM
GO