CREATE FUNCTION RANGE_DATAS(@DATA_INICIAL DATETIME,@DATA_FINAL DATETIME)
RETURNS VARCHAR(MAX)
AS 
BEGIN

DECLARE @DATA_TEMP AS DATETIME
DECLARE @COUNT AS INT
DECLARE @LIMITE AS INT
DECLARE @RETORNO AS VARCHAR(MAX)
DECLARE @MES AS VARCHAR(2)
DECLARE @ANO AS CHAR(4)

------------------------------------------------
-- PARA TESTE
------------------------------------------------
-- DECLARE @DATA_INICIAL AS DATETIME
-- DECLARE @DATA_FINAL AS DATETIME
-- SET @DATA_INICIAL = '2012-01-01'
-- SET @DATA_FINAL = '2014-01-01'
------------------------------------------------


SET @LIMITE = DATEDIFF(MM,@DATA_INICIAL,@DATA_FINAL) + 1
SET @COUNT = 1
SET @RETORNO = ''

WHILE (@COUNT <= @LIMITE)
BEGIN	
	SET @DATA_TEMP = DATEADD(MONTH, @COUNT-1, @DATA_INICIAL)
	SET @ANO = DATEPART(YEAR, @DATA_TEMP)	
	SET @MES = DATEPART(MONTH, @DATA_TEMP)
	SET @RETORNO = @RETORNO + '[' + @MES + '/' + @ANO +']'
	IF (@COUNT <> @LIMITE )	SET @RETORNO = @RETORNO + ','
	SET @COUNT = @COUNT + 1
END

RETURN @RETORNO

END


Select dbo.range_datas ('2012-01-01', '2020-12-01')