CREATE TABLE TB_CARGO (
	CD_CARGO	int			NOT NULL,
	CD_CLIENTE	int			NOT NULL,
	[Descricao]	varchar(90)	NOT NULL,
 CONSTRAINT [PK_Cargo] PRIMARY KEY CLUSTERED (CD_CLIENTE ASC, CD_CARGO ASC)
) ON [PRIMARY]
GO

INSERT INTO TB_CARGO VALUES (1, 2, 'CARGO 1')
INSERT INTO TB_CARGO VALUES (2, 1, 'CARGO 2')
INSERT INTO TB_CARGO VALUES (3, 0, 'CARGO 3')
GO

SELECT * FROM TB_CARGO;
GO

-----------------------------------------

--CORRIGINDO A ORDENAÇÃO
CREATE TABLE TB_CARGO_NOVO (
	CD_CARGO	int			NOT NULL,
	CD_CLIENTE	int			NOT NULL,
	[Descricao]	varchar(90)	NOT NULL,
 CONSTRAINT [PK_TB_Cargo] PRIMARY KEY CLUSTERED (CD_CARGO ASC, CD_CLIENTE ASC)
) ON [PRIMARY]
GO

INSERT INTO TB_CARGO_NOVO
SELECT * FROM TB_CARGO;
GO

--SUBSTITUINDO A TABELA "ATUAL"
DROP TABLE TB_CARGO;
GO

EXEC sp_rename 'TB_CARGO_NOVO', 'TB_CARGO';
GO

SELECT * FROM TB_CARGO;
GO