SELECT 
  DES.SESSION_ID,
  DES.CPU_TIME,
  DES.READS,
  DES.WRITES,
  DES.LOGICAL_READS,
  DES.ROW_COUNT,
  DER.SESSION_ID,
  DES.STATUS,
  DES.HOST_NAME,
  DES.PROGRAM_NAME,
  DES.LOGIN_NAME,
  DES.ORIGINAL_LOGIN_NAME, 
  DEC.CLIENT_NET_ADDRESS,
  DEC.AUTH_SCHEME,
  DEC.NET_TRANSPORT,
  SUBSTRING(T.[TEXT], DER.[STATEMENT_START_OFFSET] / 2, 
	COALESCE(NULLIF(DER.[STATEMENT_END_OFFSET], - 1) / 2, 2147483647)) AS COMANDO
FROM
 SYS.DM_EXEC_SESSIONS AS DES 
  INNER JOIN SYS.DM_EXEC_REQUESTS DER
   ON DER.SESSION_ID = DES.SESSION_ID
  INNER JOIN SYS.DM_EXEC_CONNECTIONS DEC  
   ON DEC.SESSION_ID = DES.SESSION_ID
  INNER JOIN SYS.DM_EXEC_REQUESTS DER2
   ON DER2.SESSION_ID = DES.SESSION_ID
   CROSS APPLY SYS.DM_EXEC_SQL_TEXT(DER.[SQL_HANDLE]) AS T
GO