UPDATE CADMICROS
SET PROCESSADOR = 'VIA Cyrix 6x86 MX 200'
WHERE NOMEUSUARIO = 'Sueli'


SELECT * FROM CADMICROS


SELECT * FROM TABELA

INSERT INTO TABELA(CODIGO,NOME,DIA,VOTOS)
VALUES (6,'EDUARDO',2002-11-20,100)

UPDATE TABELA
SET DIA = '2002-11-20'
WHERE NOME='EDUARDO'

UPDATE TABELA
SET DIA=2002-08-10
WHERE NOME='TESTE'

ALTER TABLE TABELA
ADD VOTOS4 INT

