DECLARE @A TABLE (a INT NOT NULL)
DECLARE @B TABLE (b INT NOT NULL)

SELECT COUNT_BIG(*)
FROM @A
LEFT HASH JOIN @B ON [@B].b = [@A].a

SELECT COUNT_BIG(*)
FROM @A
RIGHT HASH JOIN @B ON [@B].b = [@A].a