/* *********************************************************** */
--CRIANDO O BANCO DE DADOS IMPACTA
CREATE DATABASE IMPACTA

--ACESSANDO O BANCO DE DADOS IMPACTA
USE IMPACTA

--CRIANDO A TABELA ALUNO
CREATE TABLE ALUNO
(
  COD_ALUNO INT,
  NOME_ALUNO CHAR(30),
  RENDA_ALUNO DECIMAL(10,2)
)

--CRIANDO A TABELA PROFESSOR
CREATE TABLE PROFESSOR
(
  COD_PROF INT,
  NOME_PROF CHAR(30),
  DATA_CADPROF DATETIME
)

--INSERINDO DADOS NA TABELA ALUNO
INSERT ALUNO VALUES(1,'BIA',1500.23)
INSERT ALUNO VALUES(2,'BIANCA',700.35)
INSERT ALUNO VALUES(3,'BEATRIZ',800.50)
INSERT ALUNO VALUES(4,'DANIELA',900.53)
INSERT ALUNO VALUES(5,'EMERSON',1000.00)

--INSERINDO DADOS NA TABELA PROFESSOR

INSERT PROFESSOR VALUES(1,'JOÃO','01/01/2001')
INSERT PROFESSOR VALUES(2,'JOSÉ','02/02/2002')
INSERT PROFESSOR VALUES(3,'JOAQUIM','03/03/2003')
INSERT PROFESSOR VALUES(4,'JAIRO','04/04/2004')
INSERT PROFESSOR VALUES(5,'JONAS','05/05/2005')

select * from professor

/* *********************************************************** */

USE MASTER

DROP DATABASE IMPACTA