CREATE NONCLUSTERED INDEX ID_CTENTRADA_PQC_RESULTADOS_NUMMP ON CTENTRADA_PQC_RESULTADOS (NUMMP ASC)

CREATE NONCLUSTERED INDEX ID_PRODUTOSQUIMICOS_CODSEQUENCIALPRODUTO ON PRODUTOSQUIMICOS (CODSEQUENCI

CREATE UNIQUE NONCLUSTERED INDEX ID_CTENTRADA_PQC_RESULTADOS_NUMMP ON CTENTRADA_PQC_RESULTADOS (NUMMP ASC)

CREATE INDEX ID_CTENTRADA_PQC_RESULTADOS_NUMMP ON CTENTRADA_PQC_RESULTADOS (NUMMP ASC)


sp_configure 'fill factor'

DBCC ShowContig 

update statistics maquinas

dbcc show_statistics(produtos,pk_produtos)

set statistics io on
select * from produtos
where codigo like '1%'

