USE tempdb;
go

CREATE LOGIN SSC_Question 
  WITH PASSWORD = 'SSC', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

CREATE USER SSC WITHOUT LOGIN;

ALTER USER SSC WITH LOGIN=SSC_Question

DROP USER SSC

DROP LOGIN SSC_Question