IF DB_ID(‘Empresas’) IS NOT NULL
BEGIN
    ALTER DATABASE Empresas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Empresas;
END
GO
  
IF DB_ID(‘Marketing’) IS NOT NULL
BEGIN
    ALTER DATABASE Marketing SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Marketing;
END
GO
  
IF DB_ID(‘Produtos’) IS NOT NULL
BEGIN
    ALTER DATABASE Produtos SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Produtos;
END
GO
  
CREATE DATABASE Empresas;
GO
ALTER DATABASE Empresas SET RECOVERY FULL;
  
  
CREATE DATABASE Marketing;
GO
ALTER DATABASE Marketing SET RECOVERY FULL;
  
  
CREATE DATABASE Produtos;
GO
ALTER DATABASE Produtos SET RECOVERY FULL;
  
go
  
USE Empresas;
GO
IF OBJECT_ID(‘Dados’) IS NOT NULL
BEGIN
    DROP TABLE Dados;
END
GO
  
CREATE TABLE Dados
    (RowID INT IDENTITY PRIMARY KEY,
     Col1 INT,
     Col2 CHAR(10) DEFAULT(‘ABC123'),
     Col3 NCHAR(20) DEFAULT(’789XYZ’));
GO
  
DECLARE @StartTime DATETIME = CURRENT_TIMESTAMP;
DECLARE @Loop INT = 1;
  
BEGIN TRANSACTION
WHILE @Loop <= 100000
BEGIN
    INSERT INTO Dados (Col1) VALUES (@loop);
    SET @Loop = @Loop + 1;
END
COMMIT TRANSACTION
SELECT DATEDIFF(ms, @StartTime, CURRENT_TIMESTAMP) AS Table1_Time;
GO
  
UPDATE Dados
SET Col1 = RowID;
GO
  
USE master
GO
  
BACKUP DATABASE Empresas TO DISK = N’C:\InfoAlwaysOn\BackupAlwaysOn\Empresas.bak’;
BACKUP DATABASE Marketing TO DISK =N’C:\InfoAlwaysOn\BackupAlwaysOn\Marketing.bak’;
BACKUP DATABASE Produtos TO DISK = N’C:\InfoAlwaysOn\BackupAlwaysOn\Produtos.bak’;
GO
  
2 ª Máquina do SQL Server
 
IF DB_ID(‘Empresas’) IS NOT NULL
BEGIN
ALTER DATABASE Empresas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Empresas;
END
GO

IF DB_ID(‘Marketing’) IS NOT NULL
BEGIN
ALTER DATABASE Marketing SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Marketing;
END
GO

IF DB_ID(‘Produtos’) IS NOT NULL
BEGIN
ALTER DATABASE Produtos SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Produtos;
END
GO

3ª Máquina do SQL Server
IF DB_ID(‘Empresas’) IS NOT NULL
BEGIN
ALTER DATABASE Empresas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Empresas;
END
GO

IF DB_ID(‘Marketing’) IS NOT NULL
BEGIN
ALTER DATABASE Marketing SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Marketing;
END
GO

IF DB_ID(‘Produtos’) IS NOT NULL
BEGIN
ALTER DATABASE Produtos SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Produtos;
END
GO