USE LABORATORIO

DECLARE @DataAtual DATETIME
SET @DataAtual = GetDATE()
SELECT CAST(@DataAtual AS INTEGER) AS DATA,DATATESTE=@DataAtual-180
(SELECT * FROM INSPECAOLUVAS WHERE DATAPRODUCAO=CAST(@DataAtual AS DATETIME(10)))

