CREATE TABLE DECIPHER_TEST (COL1 INT IDENTITY NOT NULL, STAT_CODE INT NOT NULL)
 GO

CREATE INDEX DECIPHER_TEST_IND_1 ON DECIPHER_TEST (STAT_CODE)
 GO

SET NOCOUNT ON
 GO

DECLARE @I INT
 SET @I = 1
 WHILE (@I <= 1000000)
 BEGIN
 IF @I <=10
 INSERT INTO DECIPHER_TEST (STAT_CODE) VALUES (0)

IF (@I > 10 AND @I <= 10000)
 INSERT INTO DECIPHER_TEST (STAT_CODE) VALUES (30)

IF (@I > 10000 AND @I <= 1000000)
 INSERT INTO DECIPHER_TEST (STAT_CODE) VALUES (90)

SET @I = @I + 1
 END

SELECT STAT_CODE, COUNT(*) CNT_DISTR FROM DECIPHER_TEST GROUP BY STAT_CODE

UPDATE STATISTICS DECIPHER_TEST WITH SAMPLE 100 PERCENT, ALL

SET SHOWPLAN_TEXT ON
GO

DECLARE @STAT_CODE INT
 SET @STAT_CODE = 90

SELECT * FROM DECIPHER_TEST WHERE STAT_CODE = @STAT_CODE


DECLARE @STAT_CODE INT
 SET @STAT_CODE = 0

SELECT * FROM DECIPHER_TEST WHERE STAT_CODE = @STAT_CODE OPTION (OPTIMIZE FOR (@STAT_CODE = 0))
