CREATE TABLE CLIENTES
 (CODIGO INT IDENTITY(1,1),
   NOME VARCHAR(20), 
   UF CHAR(2) DEFAULT 'SP')
   
   
   INSERT INTO CLIENTES VALUES ('PEDRO','SP')
   INSERT INTO CLIENTES VALUES ('JUNIOR','SP')
   INSERT INTO CLIENTES VALUES ('ANTONIO','SP')
   
   INSERT INTO CLIENTES VALUES ('SILVA','RJ')
   INSERT INTO CLIENTES VALUES ('SILVIO','RJ')  
   
   INSERT INTO CLIENTES VALUES ('ANDRE','AC')
   
   INSERT INTO CLIENTES VALUES ('FERNANDA','MG')
   INSERT INTO CLIENTES VALUES ('FERNANDO','MG')
   
   SELECT * FROM CLIENTES
   
 ;WITH Estados (SP, RJ, MG, AC)
   AS 
   (
     Select Distinct 
      (SELECT COUNT(CODIGO) FROM CLIENTES WHERE UF='SP') AS SP,
      (SELECT COUNT(CODIGO) FROM CLIENTES WHERE UF='MG') AS MG, 
      (SELECT COUNT(CODIGO) FROM CLIENTES WHERE UF='RJ') AS RJ, 
      (SELECT COUNT(CODIGO) FROM CLIENTES WHERE UF='AC') AS AC 
     From Clientes
   ) 
   
SELECT * FROM Estados