-- Table variable --
DECLARE @test TABLE (id int, pname varchar(100))

BEGIN TRANSACTION T1
 INSERT INTO @test VALUES (1,'AAAA') 
 BEGIN TRANSACTION T2
 INSERT INTO @test VALUES (2,'BBBB')
 COMMIT TRANSACTION T2
ROLLBACK TRANSACTION T1

SELECT * FROM @test
Go

-- Physical Table --
Create TABLE Test (id int, pname varchar(100))

BEGIN TRANSACTION T1
 INSERT INTO test VALUES (1,'AAAA') 
 BEGIN TRANSACTION T2
 INSERT INTO test VALUES (2,'BBBB')
 COMMIT TRANSACTION T2
ROLLBACK TRANSACTION T1

SELECT * FROM test
Go