RESTORE FILELISTONLY 
   FROM DISK = 'W:\SYS\MSSQL_BACKUP\EXEMPLOSQL7.bak'

RESTORE DATABASE CORPORERM_CHRONUS
   FROM DISK = 'W:\SYS\MSSQL_BACKUP\EXEMPLOSQL7.bak'
   WITH MOVE 'CORPORERM_CHRONUS' TO 'W:\SYS\MSSQL_DADOS\CORPORERM_CHRONUS_DATA.mdf',
   MOVE 'CORPORERM_CHRONUS_log' TO 'W:\SYS\MSSQL_DADOS\CORPORERM_CHRONUS_LOG.ldf'
