--MASTER DATABASE
BACKUP DATABASE MASTER
TO DISK = 'T:\BACKUPS\master.bak'
WITH INIT
--MSDB DATABASE
BACKUP DATABASE MSDB
TO DISK = 'T:\BACKUPS\msdb.bak'
WITH INIT
--MODEL DATABASE
BACKUP DATABASE MODEL
TO DISK = 'T:\BACKUPS\model.bak'
WITH INIT

--

--MSDB DATABASE
RESTORE DATABASE MSDB
FROM DISK = 'T:\BACKUPS\msdb.bak'
--MODEL DATABASE
RESTORE DATABASE MODEL
FROM DISK = 'T:\BACKUPS\model.bak'
WITH REPLACE



