SELECT [Current LSN],
       Operation,
       Context,
       [Transaction ID],
       LogBlockGeneration,
       [Tag Bits],
       [Log Record Fixed Length],
       [Log Record Length],
       [Previous LSN],
       [Flag Bits],
       [Log Reserve],
       AllocUnitId,
       AllocUnitName,
       [Page ID],
       [Slot ID],
       [Previous Page LSN],
       PartitionId,
       RowFlags,
       [Num Elements],
       [Offset in Row],
       [Modify Size],
       [Checkpoint Begin],
       [CHKPT Begin DB Version],
       [Max XDESID],
       [Num Transactions],
       [Checkpoint End],
       [CHKPT End DB Version],
       [Minimum LSN],
       [Dirty Pages],
       [Oldest Replicated Begin LSN],
       [Next Replicated End LSN],
       [Last Distributed Backup End LSN],
       [Last Distributed End LSN],
       [Repl Min Hold LSN],
       [Server UID],
       SPID,
       [Beginlog Status],
       [Xact Type],
       [Begin Time],
       [Transaction Name],
       [Transaction SID],
       [Parent Transaction ID],
       [Oldest Active Transaction ID],
       [Xact ID],
       [Xact Node ID],
       [Xact Node Local ID],
       [End AGE],
       [End Time],
       [Transaction Begin],
       [Replicated Records],
       [Oldest Active LSN],
       [Server Name],
       [Database Name],
       [Mark Name],
       [Repl Partition ID],
       [Repl Epoch],
       [Repl CSN],
       [Repl Flags],
       [Repl Msg],
       [Repl Source Commit Time],
       [Master XDESID],
       [Master DBID],
       [Preplog Begin LSN],
       [Prepare Time],
       [Virtual Clock],
       [Previous Savepoint],
       [Savepoint Name],
       [Rowbits First Bit],
       [Rowbits Bit Count],
       [Rowbits Bit Value],
       [Number of Locks],
       [Lock Information],
       [LSN before writes],
       [Pages Written],
       [Command Type],
       [Publication ID],
       [Article ID],
       [Partial Status],
       Command,
       [Byte Offset],
       [New Value],
       [Old Value],
       [New Split Page],
       [Rows Deleted],
       [Bytes Freed],
       [CI Table Id],
       [CI Index Id],
       NewAllocUnitId,
       [FileGroup ID],
       [Meta Status],
       [File Status],
       [File ID],
       [Physical Name],
       [Logical Name],
       [Format LSN],
       RowsetId,
       TextPtr,
       [Column Offset],
       Flags,
       [Text Size],
       Offset,
       [Old Size],
       [New Size],
       Description,
       [Bulk allocated extent count],
       [Bulk RowsetId],
       [Bulk AllocUnitId],
       [Bulk allocation first IAM Page ID],
       [Bulk allocated extent ids],
       [VLFs added],
       [InvalidateCache Id],
       [InvalidateCache keys],
       [CopyVerionInfo Source Page Id],
       [CopyVerionInfo Source Page LSN],
       [CopyVerionInfo Source Slot Id],
       [CopyVerionInfo Source Slot Count],
       [RowLog Contents 0],
       [RowLog Contents 1],
       [RowLog Contents 2],
       [RowLog Contents 3],
       [RowLog Contents 4],
       [RowLog Contents 5],
       [Compression Log Type],
       [Compression Info],
       [PageFormat PageType],
       [PageFormat PageFlags],
       [PageFormat PageLevel],
       [PageFormat PageStat],
       [PageFormat FormatOption],
       [Log Record] FROM fn_dblog(NULL, NULL);
GO