Set NoCount On

DECLARE @NUMMO CHAR(7),
             @NUMERO VARCHAR(4)

SET @NUMMO='4203/07'
SET @NUMERO='AG06'

PRINT '*** Antes ***'
SELECT NUMMO, CODIGO_ESTOQUE FROM CTPRODUCAO_MOINHO
WHERE NUMMO=@NUMMO

UPDATE CTPRODUCAO_MOINHO
SET CODIGO_ESTOQUE=(SELECT CODIGO FROM CTProducao_Moinho_Estoque WHERE NUMERO = ''+@NUMERO+'')
WHERE NUMMO=@NUMMO

PRINT '*** Depois ***'
SELECT NUMMO, CODIGO_ESTOQUE FROM CTPRODUCAO_MOINHO
WHERE NUMMO=@NUMMO





