DECLARE @CONTADOR INT,
             @CODSEQUENCIALPRODUTO INT
SET @CONTADOR=1

DECLARE NUMMP_CURSOR CURSOR FOR
SELECT * FROM #CODSEQUENCIALPRODUTO
OPEN NUMMP_CURSOR

WHILE @CONTADOR <=109
Begin

 FETCH NEXT FROM NUMMP_CURSOR
 INTO @CODSEQUENCIALPRODUTO
 
 UPDATE CTENTRADA_PQC_RESULTADOS
 SET CODRELACIONAMENTO = (SELECT TOP 1 PQCx.CODRELACIONAMENTO
                                                FROM PQCxME PQCx INNER JOIN CTENTRADA_PQC_RESULTADOS CT
                                                                                      ON PQCx.CodSequencialProduto = CT.CODSEQUENCIALPRODUTO
                                                WHERE PQCx.CODSEQUENCIALPRODUTO=@CODSEQUENCIALPRODUTO)
 WHERE CTENTRADA_PQC_RESULTADOS.CODSEQUENCIALPRODUTO=@CODSEQUENCIALPRODUTO

/* UPDATE CTENTRADA_PQC_RESULTADOS
 SET CODSEQUENCIALPRODUTO = (SELECT TOP 1 PQ.CODSEQUENCIALPRODUTO 
                                                FROM PRODUTOSQUIMICOS PQ INNER JOIN CTENTRADA_PQC CT 
                                                                                      ON PQ.NUMCADASTRO = CT.NUMCADASTRO
                                                WHERE PQ.NUMCADASTRO=@NUMEROCADASTRO)
 WHERE CTENTRADA_PQC_RESULTADOS.NUMMP=@NUMEROMP*/

 Set @Contador=@Contador+1
End

Close NumMP_Cursor
Deallocate NumMP_Cursor

--SELECT DISTINCT(CODSEQUENCIALPRODUTO) INTO #CODSEQUENCIALPRODUTO FROM PQCXME


SELECT CODSEQUENCIALMETODO,CODSEQUENCIALPRODUTO, CODRELACIONAMENTO FROM CTENTRADA_PQC_RESULTADOS
 WHERE CODSEQUENCIALPRODUTO=6007

UPDATE CTENTRADA_PQC_RESULTADOS
 SET CODRELACIONAMENTO = (SELECT TOP 1 PQCx.CODRELACIONAMENTO
                                                FROM PQCxME PQCx INNER JOIN CTENTRADA_PQC_RESULTADOS CT
                                                                                      ON PQCx.CodSequencialProduto = CT.CODSEQUENCIALPRODUTO
                                                WHERE PQCx.CODSEQUENCIALPRODUTO=6007)
 WHERE CTENTRADA_PQC_RESULTADOS.CODSEQUENCIALPRODUTO=6007


SELECT * FROM CTENTRADA_PQC
WHERE NUMMP='0001/07'

SELECT * FROM PRODUTOSQUIMICOS
WHERE NUMCADASTRO=24

SELECT * FROM CTENTRADA_PQC_RESULTADOS
WHERE CODSEQUENCIALPRODUTO=6007


SELECT * FROM PQCXME
WHERE CODRELACIONAMENTO=67



