UPDATE CTBALOES
 SET RESP_SECAO_BALAO='E'
 WHERE MAQUINA BETWEEN 6 AND 11

UPDATE CTBALOES
 SET RESP_SECAO_BALAO='J'
 WHERE MAQUINA=3
 OR       MAQUINA BETWEEN 12 AND 14
 OR       MAQUINA=19

UPDATE CTBALOES
 SET RESP_SECAO_BALAO='O'
 WHERE MAQUINA BETWEEN 15 AND 16

SELECT MAQUINA,RESP_SECAO_BALAO FROM CTBALOES
WHERE MAQUINA=1
/*******************************************************/
SELECT * FROM MAQUINAS

ALTER TABLE MAQUINAS
 ADD RESP_SECAO CHAR(1) NULL

UPDATE MAQUINAS
 SET RESP_SECAO='E'
 WHERE CODMAQUINA BETWEEN 6 AND 11

UPDATE MAQUINAS
 SET RESP_SECAO='J'
 WHERE CODMAQUINA=3
 OR       CODMAQUINA BETWEEN 12 AND 14
 OR       CODMAQUINA=19

UPDATE MAQUINAS
 SET RESP_SECAO='O'
 WHERE CODMAQUINA BETWEEN 15 AND 16
/*******************************************************/
SELECT * FROM CTBALOES
WHERE DATEPART(YEAR,DATATESTE)=2003
ORDER BY DATATESTE DESC
/*******************************************************/
SELECT CONTADOR=(SELECT COUNT(NUMTESTE) FROM CTBALOES
WHERE DATEPART(YEAR,DATATESTE)=2003), * FROM CTBALOES
WHERE DATEPART(YEAR,DATATESTE)=2003
ORDER BY NUMTESTE
/*******************************************************/
SELECT PRO.CODIGO, PRO.DESCRICAO, CT.* 
FROM PRODUTOS PRO INNER JOIN CTBALOES CT
                              ON PRO.CODIGO = CT.CODPRODUTO
WHERE CT.RESP_SECAO_BALAO IN('E','J','O')
ORDER BY CT.CODPRODUTO
/*******************************************************/
SELECT PRO.CODIGO, PRO.DESCRICAO, CT.* 
FROM PRODUTOS PRO INNER JOIN CTBALOES CT
                              ON PRO.CODIGO = CT.CODPRODUTO
WHERE CT.RESP_SECAO_BALAO IN('E','J','O')
AND CT.DATATESTE BETWEEN '2004-01-01' AND '2004-01-04'
ORDER BY CT.RESP_SECAO_BALAO,CT.MAQUINA
/*******************************************************/
