DECLARE @RESULTADO1 Int,
        @RESULTADO2 Int,
        @RESULTADO3 Int,
        @RESULTADO4 Int   

SET @RESULTADO1=(SELECT MAX(NUMFICHA)-MIN(NUMFICHA) FROM CUSTO100..CUSTO)
SET @RESULTADO2=(SELECT MAX(NUMFICHA)-MIN(NUMFICHA) FROM CUSTO200..CUSTO)
SET @RESULTADO3=(SELECT MAX(NUMFICHA)-MIN(NUMFICHA) FROM CUSTO300..CUSTO)
SET @RESULTADO4=(SELECT MAX(NUMFICHA)-MIN(NUMFICHA) FROM CUSTO900..CUSTO)

PRINT 'Resultado Final:'+Cast(@RESULTADO1+@RESULTADO2+@RESULTADO3+@RESULTADO4 as Char(8))