CREATE TABLE CLASSES_QUIMICAS
 (
   CODIGO INT IDENTITY(1,1),
   DESCRICAO VARCHAR(50) NOT NULL)


ALTER TABLE CLASSES_QUIMICAS
 ADD CONSTRAINT [PK_CODIGO_CLASSES_QUIMICAS] PRIMARY KEY (CODIGO)


CREATE TABLE PRODUTOS_QUIMICOS
 (
  CODSEQUENCIAL INT IDENTITY(1,1),
  CODPRODUTO INT NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL,
  CODFORNECEDOR INT NOT NULL,
  CODCLASSE INT NOT NULL,
  NUMPASTA INT NOT NULL)


ALTER TABLE PRODUTOS_QUIMICOS
 ADD CONSTRAINT [PK_CODPRODUTO_PRODUTOS_QUIMICOS] PRIMARY KEY (CODSEQUENCIAL)




