CREATE TABLE CLASSIFICACAO_ME
 (
   CODIGO INT IDENTITY(1,1),
   DESCRICAO VARCHAR(100) NOT NULL,
   CLASSE CHAR(5) NOT NULL,
   SIGLA CHAR(2) NOT NULL)


ALTER TABLE CLASSIFICACAO_ME
 ADD CONSTRAINT [PK_CODIGO_CLASSIFICACAO_ME] PRIMARY KEY (CODIGO)

CREATE TABLE METODOS_ENSAIOS
 (
   CODIGO INT IDENTITY(1,1),
   NUMENSAIO INT,
   DESCRICAO VARCHAR(100) NOT NULL,
   NUMCLASSE INT)

ALTER TABLE METODOS_ENSAIOS
 ADD CONSTRAINT [PK_CODIGO_METODOS_ENSAIOS] PRIMARY KEY (CODIGO)


SELECT * FROM CLASSIFICACAO_ME

INSERT INTO CLASSIFICACAO_ME VALUES('Laboratório Químico','ME/LQ','LQ')



