CREATE TABLE CTENTRADA_PQC
(
 CODSEQUENCIAL INT IDENTITY(1,1), 
 CODSIGLA      CHAR(2) NOT NULL,
 CODPRODUTO    INT     NOT NULL,
 DESCFORNEC    VARCHAR(50) NOT NULL,
 DATAALMOX     DATETIME NOT NULL,
 DATALAB       DATETIME NOT NULL,
 CODFORNEC     INT     NOT NULL,
 NUMNTFISCAL   INT     NOT NULL,
 NUMLOTE       VARCHAR(25)   NOT NULL,
 QUANTIDADE    FLOAT   NOT NULL, 
 DATAVALIDADE  DATETIME NOT NULL,
 CODRESP       INT     NOT NULL,
 STATUS        CHAR(1) NOT NULL,
 NUMMP         CHAR(7) NOT NULL,
 MOTIVO        VARCHAR(100) NULL,
 ACAO          VARCHAR(100) NULL)

ALTER TABLE CTENTRADA_PQC
 ADD CONSTRAINT [PK_CODSEQUENCIAL] PRIMARY KEY (CODSEQUENCIAL)

ALTER TABLE CTENTRADA_PQC
 ADD CONSTRAINT [DF_CODSIGLA] DEFAULT 'MP' FOR CODSIGLA 

ALTER TABLE CTENTRADA_PQC
 ADD CONSTRAINT [DF_DATACONTROLE] DEFAULT GETDATE() FOR DATACONTROLE


Alter PROCEDURE P_Formatar_NumeroMP
As
 UPDATE CTENTRADA_PQC
 SET NUMMP=(SELECT 
             CASE LEN(CODSEQUENCIAL)
              WHEN 1 THEN REPLICATE('0',3)+CONVERT(CHAR(1),CODSEQUENCIAL)+'/'+SUBSTRING(CONVERT(CHAR(4),DATEPART(YEAR,GETDATE())),3,2)
              WHEN 2 THEN REPLICATE('0',2)+CONVERT(CHAR(2),CODSEQUENCIAL)+'/'+SUBSTRING(CONVERT(CHAR(4),DATEPART(YEAR,GETDATE())),3,2)
              WHEN 3 THEN REPLICATE('0',1)+CONVERT(CHAR(3),CODSEQUENCIAL)+'/'+SUBSTRING(CONVERT(CHAR(4),DATEPART(YEAR,GETDATE())),3,2)
             END
             From CTENTRADA_PQC)
WHERE CODSEQUENCIAL IN (SELECT MAX(CODSEQUENCIAL) FROM CTENTRADA_PQC) 
                                           


ALTER TABLE CTENTRADA_PQC
 DROP COLUMN DATACONTROLE
  

SELECT SUBSTRING(CONVERT(CHAR(4),DATEPART(YEAR,GETDATE())),3,2)