CREATE TABLE PRODUTOSQUIMICOS
 (
  NUMCADASTRO   INT NOT NULL,
  CODANTIGO     VARCHAR(9)  NOT NULL,
  DESCRICAO     VARCHAR(50) NOT NULL,
  DESCFORNEC    VARCHAR(50) NOT NULL,
  CODCLASSE     INT         NOT NULL
 )
  
ALTER TABLE PRODUTOSQUIMICOS
 alter column codantigo int not null

 ADD CONSTRAINT [PK_NUMCADASTRO] PRIMARY KEY (NUMCADASTRO)

CREATE UNIQUE INDEX 
 ID_CODANTIGO ON PRODUTOSQUIMICOS(CODANTIGO)

drop index produtosquimicos.Id_codantigo

SELECT * FROM CLASSES_QUIMICAS