PRINT 'RELATÓRIO DE PRODUTOS - GOL x DATAFLEX '+CAST(GETDATE() AS VARCHAR(20))

PRINT ''

SELECT PG.CODIGO AS 'CODIGO GOL',
           PG.DESCRICAO AS 'DESCRICAO GOL',
           ISNULL(PD.CODIGO,'                         ') AS 'CODIGO DATAFLEX',
           ISNULL(PD.DESCRICAO,'                                                                              ') AS 'DESCRICAO DATAFLEX'
FROM PRODUTOS_GOL PG INNER JOIN PRODUTOS_DTFLEX PD
                                    ON PG.CODIGO = PD.CODIGO
 WHERE     PG.CODIGO LIKE '1%' AND LEN(PG.CODIGO) =9
 OR           PG.CODIGO LIKE '[2-6,9]%' AND LEN(PG.CODIGO) >= 6 
 AND         PG.DESCRICAO <> ' '
ORDER BY PG.CODIGO



PRINT 'RELATÓRIO DE PRODUTOS - CADASTRADOS NO DATAFLEX x NÃO CADASTRADOS NO GOL '+CAST(GETDATE() AS VARCHAR(20))

PRINT ''

SELECT PD.CODIGO,
           PD.DESCRICAO
FROM   PRODUTOS_DTFLEX PD
WHERE NOT EXISTS(SELECT CODIGO 
                            FROM PRODUTOS_GOL PG
                             WHERE PG.CODIGO = PD.CODIGO)
 AND    PD.DESCRICAO <> ' '
ORDER BY PD.CODIGO


