SELECT CT.CODPRODUTO, CT.LOTEINTERNO, CT.LOTEPRODUCAO, CONVERT(CHAR(10),CT.DATAPRODUCAO,103), LT.DIA+'/'+LT.MES+'/'+LT.ANO, CT.DATAREVISAO
FROM CTLUVAS CT INNER JOIN LOTEPRODUCAO LT
                 ON SUBSTRING(CT.LOTEPRODUCAO,1,5) = LT.LOTE
WHERE CONVERT(CHAR(10),DATAPRODUCAO,103)='01/06/2006'
AND   LT.DIA <> '01' AND MES <> '06'
AND   MONTH(DATAREVISAO) <> MONTH(DATAPRODUCAO)
AND   MAQUINA = 9
