DECLARE @NUMREQUISICAO INT,
             @LOTEINI INT
             
SET @NUMREQUISICAO=1
SET @LOTEINI=(SELECT MIN(LOTEPRODUCAO) FROM MOVIMENTACAO_LOTEPRODUCAO)

WHILE @LOTEINI <=(SELECT MAX(LOTEPRODUCAO) FROM MOVIMENTACAO_LOTEPRODUCAO)
 Begin

  IF @LOTEINI >(select max(loteproducao) from movimentacao_loteproducao)
   Break
  Else
   Begin 
    BEGIN TRANSACTION  

    UPDATE MOVIMENTACAO_LOTEPRODUCAO
    SET NUMREQUISICAO=@NUMREQUISICAO
    WHERE LOTEPRODUCAO=@LOTEINI

    COMMIT

    SET @NUMREQUISICAO=@NUMREQUISICAO+1
   End

  SET @LOTEINI=(SELECT TOP 1 LOTEPRODUCAO FROM MOVIMENTACAO_LOTEPRODUCAO WHERE LOTEPRODUCAO >@LOTEINI ORDER BY LOTEPRODUCAO)
 End
/****************************************************/
SELECT * FROM MOVIMENTACAO_LOTEPRODUCAO
ORDER BY NUMREQUISICAO

