SELECT * FROM TRANSFERENCIAS
WHERE CODDESTINO='L'
and CODPRODUTO LIKE '[3-4]%'
ORDER BY CODPRODUTO

SELECT TRA.CODIGO,
           TRA.CODPRODUTO,           
           PRO.DESCRICAO,
           SUM(TRA.QUANTIDADE) AS QUANTIDADE,
           SUM(ROUND(TRA.PESO,2)) AS PESO,                 
           SUM(TRA.QUANTCAIXAS) AS QUANTCAIXAS
FROM  TRANSFERENCIAS TRA INNER JOIN PRODUTOS_NF PRO
                                         ON CONVERT(VARCHAR(24),TRA.CODPRODUTO) = PRO.CODPRODUTO
                                         AND     TRA.CODPRODUTO LIKE '[3-4]%'
WHERE TRA.CODDESTINO='L'
AND     YEAR(TRA.DATA)=2007
AND     MONTH(TRA.DATA)=12
GROUP BY TRA.CODIGO, TRA.CODPRODUTO, PRO.DESCRICAO
ORDER BY TRA.CODIGO, TRA.CODPRODUTO

331315	G.EXANGLO	2	17,6	20


select CODIGO, DATA  from transferencias TRA
WHERE CODIGO
