SELECT PRO.CODPRODSEQUENCIAL,
       PRO.CODANTIGO,
       PRO.DESCRICAO,
       CONVERT(CHAR(3),PRO.CATEGORIA)+' - '+CAT.DESCRICAO AS "Categoria",
       PRO.GRUPOFORNEC,
       FN.RAZAOSOCIAL
FROM CMPPRODUTOS PRO INNER JOIN GERPESSOAS FN
                      ON PRO.GRUPOFORNEC = FN.CODCADGERAL
                     INNER JOIN CMPCATPRODUTOS CAT
                      ON PRO.CATEGORIA = CAT.CODIGO
WHERE PRO.CODANTIGO LIKE '955%'
AND   PRO.GRUPOFORNEC IS NOT NULL
ORDER BY PRO.DESCRICAO

SELECT FN.CODANTIGO+' - '+FN.RAZAOSOCIAL As 'Classificação do Fornecedor',
       PRO.CODANTIGO+' - '+PRO.DESCRICAO As 'Classificação do Produto',
       CONVERT(CHAR(3),PRO.CATEGORIA)+' - '+CAT.DESCRICAO As 'Categoria do Produto'
FROM GERPESSOAS FN INNER JOIN CMPPRODUTOS PRO
                    ON FN.CODCADGERAL = PRO.GRUPOFORNEC AND PRO.GRUPOFORNEC IS NOT NULL
                   INNER JOIN CMPCATPRODUTOS CAT
                    ON PRO.CATEGORIA = CAT.CODIGO
WHERE PRO.CATEGORIA LIKE '5%'
ORDER BY PRO.DESCRICAO

SELECT * FROM CMPPRODUTOS
WHERE GRUPOFORNEC IS NULL

