SELECT CODPRODUTO AS 'CÓDIGO',
           DESCRICAO AS 'DESCRIÇÃO',
           CODBARRAS AS 'CÓDIGO DE BARRAS',
           CODDUN14 AS 'CÓDIGO DUN14',
           ISNULL(CAST(DATACADASTRO AS CHAR(20)),'') AS 'DATA DE CADASTRO'
FROM PRODUTOS
ORDER BY DATACADASTRO DESC, CODPRODUTO