SELECT PS1.CODIGO, PS1.DESCRICAO,
           PS2.CODIGO AS 'CÓD-SUBSEÇÃO', PS2.DESCRICAO AS 'DESCRIÇÃO SUBSEÇÃO'
FROM PSECAO PS1, PSECAO PS2									
WHERE LEN(PS1.CODIGO) = 8 
AND     LEN(PS2.CODIGO) = 11
AND     PS1.CODIGO=SUBSTRING(PS2.CODIGO,1,8)
ORDER BY PS1.CODIGO


SELECT PS1.CODIGO, PS1.DESCRICAO,
           PS2.CODIGO AS 'CÓD-SUBSEÇÃO', PS2.DESCRICAO AS 'DESCRIÇÃO SUBSEÇÃO'
FROM PSECAO PS1 INNER JOIN PSECAO PS2
                           ON LEN(PS1.CODIGO) = 8 
                           AND LEN(PS2.CODIGO) = 11
                           AND  PS1.CODIGO=SUBSTRING(PS2.CODIGO,1,8)
ORDER BY PS1.CODIGO
