CREATE FUNCTION dbo.FUNC_REMOVE_ACENTO ( @TEXTO VARCHAR (5000))
RETURNS VARCHAR (5000)
AS
BEGIN
DECLARE @COMACENTOS VARCHAR(50)
DECLARE @SEMACENTOS VARCHAR(50)
DECLARE @QTD_TEXTO INT
DECLARE @CONTADOR INT
DECLARE @QTD INT
DECLARE @CONT INT
DECLARE @CONT_C INT
DECLARE @LETRA_T NVARCHAR(1)
DECLARE @LETRA_C NVARCHAR(1)
DECLARE @RESULTADO VARCHAR(5000)

SET @COMACENTOS = '·¡‡¿‚¬„√È…Ë»Í ÌÕÏÃÓŒÛ”Ú“Ù‘ı’˙⁄˘Ÿ˚€¸‹Á«'
SET @SEMACENTOS = 'AAAAAAAAEEEEEEIIIIIIOOOOOOOOUUUUUUUUCC'
SET @QTD_TEXTO  = (SELECT LEN(@TEXTO))
SET @CONTADOR   = 0
SET @RESULTADO  = ''

INICIO:
WHILE @CONTADOR < @QTD_TEXTO
BEGIN
  SET @CONTADOR = @CONTADOR + 1
  SET @LETRA_T = (SELECT SUBSTRING(@TEXTO,@CONTADOR,1))
  SET @CONT = (SELECT LEN(@COMACENTOS))
  SET @QTD = 0
  WHILE @QTD < @CONT
  BEGIN
     SET @QTD = @QTD + 1
     SET @LETRA_C = (SELECT SUBSTRING(@COMACENTOS,@QTD,1))
     IF @LETRA_C = @LETRA_T
     BEGIN
        SET @RESULTADO = @RESULTADO + (SELECT SUBSTRING(@SEMACENTOS,@QTD,1))
        GOTO INICIO
     END
     ELSE
     BEGIN
        IF @QTD = @CONT
           SET @RESULTADO =  @RESULTADO + @LETRA_T
     END
  END
END

RETURN ( UPPER(@RESULTADO) )
END
GO
