CREATE FUNCTION dbo.FUNC_FONETIZAR_PARTICULA (@STR VARCHAR(5000))
RETURNS VARCHAR(5000)
AS
BEGIN
   DECLARE
      @AUX           VARCHAR(5000),
      @AUX2          VARCHAR(5000),
      @I             INT,
      @N             INT,
      @J             INT,
      @LETRAS        VARCHAR(26),
      @CODFONETICO   VARCHAR(26),
      @CARACTERES    VARCHAR(1000),
      @CARACTERESSUB VARCHAR(1000)

  /*CRIA A CODIFICAÇÃO DOS FONEMAS*/
   SET @LETRAS      = 'ABPCKQDTEIYFVWGJLMNOURSZX9'
   SET @CODFONETICO = '123444568880AABCDEEGAIJJL9'

  /*ELIMINA LETRAS IGUAIS SEGUIDAS UMA DA OUTRA*/

   SET @AUX = SUBSTRING(@STR,1,1) /*RECEBE A PRIMEIRA LETRA*/
   SET @I = 2
   
   WHILE @I <= LEN(@STR)
   BEGIN
      IF SUBSTRING(@STR,@I - 1,1) <> SUBSTRING(@STR,@I,1) 
         SET @AUX = @AUX + SUBSTRING(@STR,@I,1)
      SET @I = @I + 1
   END

  /*IGUALA FONEMAS PARECIDOS*/


  IF SUBSTRING(@AUX,1,1) = 'W'
     IF SUBSTRING(@AUX,2,1) = 'I'
        SET @AUX = 'U' + SUBSTRING(@AUX,2,LEN(@AUX)) /*TROCA W POR U*/
     ELSE
        IF SUBSTRING(@AUX,2,1) IN ('A','E','O','U')
           SET @AUX = 'V' + SUBSTRING(@AUX,2,LEN(@AUX)) /*TROCA W POR V*/
           


  SELECT @AUX = dbo.FUNC_SUBSTITUI_TERMINACAO(@AUX)

  SET @CARACTERES    = 'TSCHSCH TSH TCH SH  CH  LH  NH  PH  GN  MN  SCE SCI SCY CS  KS  PS  TS  TZ  XS  CE  CI  CY  GE  GI  GY  GD  CK  PC  QU  SC  SK  XC  SQ  CT  GT  PT  '
  SET @CARACTERESSUB = 'XXXXXXX XXX XXX XX  XX  LI  NN  FF  NN  NN  SSI SSI SSI SS  SS  SS  SS  SS  SS  SE  SI  SI  JE  JI  JI  DD  QQ  QQ  QQ  SQ  SQ  SQ  99  TT  TT  TT  '

  SET @I = 1
  WHILE @I <= 148
  BEGIN
     SELECT @AUX = REPLACE(@AUX,LTRIM(RTRIM(SUBSTRING(@CARACTERES,@I,4))), LTRIM(RTRIM(SUBSTRING(@CARACTERESSUB,@I,4))))
     SET @I = @I + 4
  END

  /*TRATAR CONSOANTES MUDAS*/
  SELECT @AUX = dbo.FUNC_TRATA_CONSOANTE_MUDA(@AUX,'B','I')
  SELECT @AUX = dbo.FUNC_TRATA_CONSOANTE_MUDA(@AUX,'D','I')
  SELECT @AUX = dbo.FUNC_TRATA_CONSOANTE_MUDA(@AUX,'P','I')

  -- TRATA LETRAS
  -- RETIRA LETRAS IGUAIS
  IF SUBSTRING(@AUX,1,1) = 'H'
  BEGIN
     SET @AUX2 = SUBSTRING(@AUX,2,1) -- RECEBE A SEGUNDA LETRA
     SET @J = 3
  END
  ELSE
  BEGIN
     SET @AUX2 = SUBSTRING(@AUX,1,1) -- RECEBE A PRIMEIRA LETRA
     SET @J = 2
  END

  WHILE @J <= LEN(@AUX)
  BEGIN
     IF (((SUBSTRING(@AUX,@J - 1,1) <> SUBSTRING(@AUX,@J,1))) AND
        (SUBSTRING(@AUX,@J,1) <> 'H'))
        SET @AUX2 = @AUX2 + SUBSTRING(@AUX,@J,1)
     SET @J = @J + 1
  END

  SET @AUX = @AUX2

  -- TRANSFORMA LETRAS EM CODIGOS FONETICOS
  SET @AUX2 = ''

  SET @I = 1

  WHILE @I <= LEN(@AUX)
  BEGIN
     SET @N = 1
     WHILE @N <= 26
     BEGIN
        IF SUBSTRING(@AUX,@I,1) = SUBSTRING(@LETRAS,@N,1)
           SET @AUX2 = @AUX2 + SUBSTRING(@CODFONETICO,@N,1)
        SET @N = @N + 1
     END
     SET @I = @I + 1
  END

  RETURN @AUX2
END
GO
