CREATE FUNCTION dbo.FUNC_SUBSTITUI_TERMINACAO (@STR VARCHAR(5000))
RETURNS VARCHAR(5000)
AS
BEGIN
   DECLARE
      @TERMINACAO    VARCHAR(1000),
      @TERMINACAOSUB VARCHAR(1000),
      @TAMANHOMINSTR VARCHAR(1000),
      @I INT

/*
SUBSTITUI AS TERMINAÇÕES CONTIDAS NO VETOR $vTerminacao PELAS DO VETOR $vTerminacaoSub RESPEITANDO
O TAMANHO MÍNIMO DA STRING CONTIDO NO VETOR $vTamanhoMinStr.
NO CASO DA STRING TERMINAR COM 'N', O LAÇO CONTINUARÁ, POIS PODERÃO EXIXTIR NOVAS SUBSTITUIÇÕES COM
A TERMINAÇÃO 'M'.
*/
      SELECT @STR = dbo.FUNC_REMOVE_ACENTO(@STR)
      
      SET @TERMINACAO    = 'N  B  D  T  W  AM OM OIMUIMCAOAO OEMONSEIAX  US TH'
      SET @TERMINACAOSUB = 'M              N  N  N  N  SSNN  N  N  IA IS OS TI'
      SET @TAMANHOMINSTR = '2  3  3  3  3  2  2  2  2  3  2  2  2  2  2  2  3'
      SET @I             = 1

   LOOP:
   BEGIN
	
      IF RTRIM(SUBSTRING(@STR,LEN(@STR) - LEN(SUBSTRING(@TERMINACAO,@I,3)) + 1,LEN(SUBSTRING(@TERMINACAO,@I,3)))) = RTRIM(SUBSTRING(@TERMINACAO,@I,3)) AND
         (LEN(@STR) >= CONVERT(INT,SUBSTRING(@TAMANHOMINSTR,@I,3)))
      BEGIN
         SET @STR = SUBSTRING(@STR,1,LEN(@STR) - LEN(SUBSTRING(@TERMINACAO,@I,3))) + RTRIM(SUBSTRING(@TERMINACAOSUB,@I,3))
         IF @I > 1
            GOTO FIM
      END
    
      SET @I = @I + 3

	  IF @I < 52
	     GOTO LOOP

   END

   FIM:
   BEGIN	
      RETURN @STR
   END

END
GO
