CREATE FUNCTION dbo.FUNC_TRATA_CONSOANTE_MUDA (@STR VARCHAR(5000), @CONSOANTE CHAR(1), @COMPLEMENTO CHAR(1))
RETURNS VARCHAR(5000)
AS
BEGIN
   DECLARE
     @I INT,
     @CONTADOR INT

/*
PARA TODAS AS OCORRÊNCIAS DA CONSOANTE $consoante QUE NÃO ESTIVER SEGUIDA DE VOGAL, SERÁ ADICIONADO
O CONTEÚDO DA VARIÁVEL $complemento NA STRING.
*/

   SET @I = LEN(@STR)
   SET @CONTADOR = 1

   LOOP:
   BEGIN

--  for i in 1..length(tStr) loop
      IF ((SUBSTRING(@STR,@CONTADOR,1) = @CONSOANTE) AND
          (SUBSTRING(@STR,@CONTADOR + 1,1) NOT IN ('A','E','I','O','U')))

          SET @STR = SUBSTRING(@STR,1,@CONTADOR) + @COMPLEMENTO + SUBSTRING(@STR,@CONTADOR + 1,LEN(@STR))

      SET @CONTADOR = @CONTADOR + 1

      IF @CONTADOR <= @I
         GOTO LOOP

    END  		

    RETURN @STR

END
GO
