DECLARE @TB_MONITORAMENTO table (CD_BANCO int, NM_BANCO varchar(50), NM_STATUS varchar(30), DT_MONITORADO datetime)

INSERT INTO @TB_MONITORAMENTO (CD_BANCO, NM_BANCO, NM_STATUS, DT_MONITORADO)
EXEC sp_MSForEachDB '
USE ?;
IF DB_ID() > 4	-- REMOVE OS BANCOS DE SISTEMA
  BEGIN
	SELECT DB_ID(), CAST(DB_NAME() AS VARCHAR), CAST(DATABASEPROPERTYEX (DB_NAME(), ''Status'') AS VARCHAR), GETDATE()
END
'

SELECT * FROM @TB_MONITORAMENTO
GO