delete from sysusers where name ='\RM'
delete from sysusers where name ='SYSDBA'

/* CRIAÇÃO DOS USUÁRIOS */

IF NOT EXISTS(SELECT * FROM MASTER.DBO.SYSLOGINS WHERE NAME = 'RM')
   EXEC SP_ADDLOGIN RM,RM
GO

sp_addalias RM,dbo
GO

IF NOT EXISTS(SELECT * FROM MASTER.DBO.SYSLOGINS WHERE NAME = 'SYSDBA')
   EXEC SP_ADDLOGIN SYSDBA,masterkey
GO
 
sp_adduser SYSDBA,SYSDBA
GO


GRANT SELECT ON GPARAMS TO SYSDBA
GO
GRANT SELECT , UPDATE ON GUSUARIO TO SYSDBA
GO
GRANT SELECT ON GPERMIS  TO SYSDBA
GO
GRANT SELECT ON GACESSO  TO SYSDBA
GO
GRANT SELECT ON GSISTEMA  TO SYSDBA
GO
GRANT SELECT ON GCOLIGADA  TO SYSDBA
GO
GRANT SELECT ON GUSRPERFIL TO SYSDBA
GO
GRANT SELECT ON WPESSOAEXT TO SYSDBA
GO
